Row -> Position
Column -> Position
Position -> cells : Array<position>
Direction (V/H) -> cells
ships -> length
ships -> ShipType
ships -> ShipName
length -> cells
ShipType -> Ship
cells -> Ship :validatePosition